class_name OptionsPanel
extends VBoxContainer
## The Options screen: Audio, Display and Gameplay tabs. Every change applies at once and is saved to
## user://options.cfg by the Options autoload.

var _tabs: HBoxContainer
var _page: VBoxContainer
var _current := "audio"


static func open_modal() -> Modal:
	var p := OptionsPanel.new()
	return Modal.open(p, "Options", 720)


func _ready() -> void:
	add_theme_constant_override("separation", 16)
	custom_minimum_size = Vector2(660, 460)
	_tabs = UI.hbox(8)
	add_child(_tabs)
	for pair in [["audio", "Audio"], ["display", "Display"], ["gameplay", "Gameplay"]]:
		var b := UI.button(pair[1], "ChipOn" if pair[0] == _current else "Chip")
		b.pressed.connect(func():
			_current = pair[0]
			_rebuild())
		_tabs.add_child(b)
	_page = UI.vbox(14)
	add_child(UI.panel("Inset", _page))
	_rebuild()


func _rebuild() -> void:
	for i in _tabs.get_child_count():
		_tabs.get_child(i).theme_type_variation = "ChipOn" if ["audio", "display", "gameplay"][i] == _current else "Chip"
	UI.clear(_page)
	match _current:
		"audio":
			_slider("Master volume", "master")
			_slider("Music", "music")
			_slider("Sound effects", "sfx")
			_toggle("Mute when the window is in the background", "mute_unfocused")
			_page.add_child(UI.wrap_label("The music is generated by the game itself: three calm loops for the title screen, the Sanctum and expeditions.", "Faint"))
		"display":
			_choice("Window mode", "window_mode", Options.WINDOW_MODES)
			var res := Options.RESOLUTIONS.map(func(r): return "%d × %d" % [r.x, r.y])
			var rb := _choice("Window size", "resolution", res)
			rb.disabled = int(Options.get_value("window_mode")) != 0
			_toggle("VSync (match the display's refresh rate)", "vsync")
			var caps := Options.FPS_CAPS.map(func(f): return "Unlimited" if f == 0 else "%d FPS" % f)
			_choice("Frame rate cap", "fps_cap", caps)
			_page.add_child(UI.label("Your display refreshes at %s." % Options.refresh_rate_text(), "Faint"))
			_choice("Frame rate in the background", "background_fps", ["5 FPS", "10 FPS", "30 FPS"], [5, 10, 30])
			_choice("Interface scale", "ui_scale", Options.UI_SCALES.map(func(s): return "%d%%" % roundi(s * 100)))
			_page.add_child(UI.wrap_label("The game keeps working at full speed in the background and while closed: frame rate only affects drawing.", "Faint"))
		"gameplay":
			_toggle("Reduce motion (no bobbing, shakes or pops)", "reduce_motion")
			_toggle("Show damage numbers in battles", "damage_numbers")
			_toggle("Screen shake on big moments", "screen_shake")
			_toggle("Toast notifications", "toasts")
			_toggle("Developer tools in the pause menu (for testing)", "dev_tools")
			_page.add_child(UI.label("Shortcuts: 1 Sanctum · 2 Nexus · 3 Genesis Pods · 4 Expeditions · 5 Aether-Log · 6 Inventory · 7 Sanctum Works · Esc menu", "Faint"))


func _row(title: String) -> HBoxContainer:
	var h := UI.hbox(12)
	var l := UI.label(title)
	l.custom_minimum_size.x = 250
	h.add_child(l)
	_page.add_child(h)
	return h


func _slider(title: String, key: String) -> void:
	var h := _row(title)
	var s := HSlider.new()
	s.min_value = 0.0
	s.max_value = 1.0
	s.step = 0.01
	s.value = float(Options.get_value(key))
	s.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	s.custom_minimum_size.y = 24
	var pct := UI.label("%d%%" % roundi(s.value * 100), "Num")
	pct.custom_minimum_size.x = 52
	pct.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	s.value_changed.connect(func(v):
		pct.text = "%d%%" % roundi(v * 100)
		Options.set_value(key, v))
	s.drag_ended.connect(func(_c): if key == "sfx" or key == "master": Sfx.play("click"))
	h.add_child(s)
	h.add_child(pct)


func _toggle(title: String, key: String) -> void:
	var c := CheckButton.new()
	c.text = title
	c.button_pressed = bool(Options.get_value(key))
	c.focus_mode = Control.FOCUS_NONE
	c.toggled.connect(func(on): Options.set_value(key, on))
	_page.add_child(c)


func _choice(title: String, key: String, labels: Array, values: Array = []) -> OptionButton:
	var h := _row(title)
	var o := OptionButton.new()
	o.focus_mode = Control.FOCUS_NONE
	o.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	for i in labels.size():
		o.add_item(labels[i], i)
	var current: Variant = Options.get_value(key)
	o.selected = values.find(current) if not values.is_empty() else int(current)
	o.item_selected.connect(func(i):
		Options.set_value(key, values[i] if not values.is_empty() else i)
		if key == "window_mode":
			_rebuild())
	h.add_child(o)
	return o
