class_name OptionsPanel
extends VBoxContainer
## The Options screen: Audio, Display, Gameplay and Controls tabs. Every change applies at once and is saved to
## user://options.cfg by the Options autoload.

var _tabs: HBoxContainer
var _page: VBoxContainer
var _current := "audio"
var _capturing := ""   # the tab waiting for a new key in Controls, or ""
const PAGES := [["audio", "Audio"], ["display", "Display"], ["gameplay", "Gameplay"], ["controls", "Controls"]]


static func open_modal() -> Modal:
	var p := OptionsPanel.new()
	return Modal.open(p, "Options", 720)


func _ready() -> void:
	add_theme_constant_override("separation", 16)
	custom_minimum_size = Vector2(660, 460)
	_tabs = UI.hbox(8)
	add_child(_tabs)
	for pair in PAGES:
		var b := UI.button(pair[1], "ChipOn" if pair[0] == _current else "Chip")
		b.pressed.connect(func():
			_current = pair[0]
			_rebuild())
		_tabs.add_child(b)
	_page = UI.vbox(14)
	add_child(UI.panel("Inset", _page))
	_rebuild()


func _rebuild() -> void:
	for i in _tabs.get_child_count():
		_tabs.get_child(i).theme_type_variation = "ChipOn" if PAGES[i][0] == _current else "Chip"
	UI.clear(_page)
	match _current:
		"audio":
			_slider("Master volume", "master")
			_slider("Music", "music")
			_slider("Sound effects", "sfx")
			_toggle("Mute when the window is in the background", "mute_unfocused")
			_page.add_child(_note("The music is generated by the game itself: loops for the title screen, the Sanctum, expeditions and boss fights."))
		"display":
			_choice("Window mode", "window_mode", Options.WINDOW_MODES)
			if int(Options.get_value("window_mode")) == 0:
				var res := Options.RESOLUTIONS.map(func(r): return "%d × %d" % [r.x, r.y])
				_choice("Window size", "resolution", res)
			else:
				# Fullscreen always uses the whole screen, so show that size instead of the windowed one.
				var scr := Options.screen_size()
				var rb := _choice("Window size", "", ["%d × %d (whole screen)" % [scr.x, scr.y]])
				rb.disabled = true
			_toggle("VSync (match the display's refresh rate)", "vsync")
			var caps := Options.FPS_CAPS.map(func(f): return "Unlimited" if f == 0 else "%d FPS" % f)
			_choice("Frame rate cap", "fps_cap", caps)
			_page.add_child(UI.label("Your display refreshes at %s." % Options.refresh_rate_text(), "Faint"))
			_choice("Frame rate in the background", "background_fps", ["5 FPS", "10 FPS", "30 FPS"], [5, 10, 30])
			_choice("Interface scale", "ui_scale", Options.UI_SCALES.map(func(s): return "%d%%" % roundi(s * 100)))
			_page.add_child(_note("The game keeps working at full speed in the background and while closed: frame rate only affects drawing."))
		"gameplay":
			_toggle("Reduce motion (no bobbing, shakes or pops)", "reduce_motion")
			_toggle("Show damage numbers in battles", "damage_numbers")
			_toggle("Screen shake on big moments", "screen_shake")
			_toggle("Toast notifications", "toasts")
			_toggle("Developer tools in the pause menu (for testing)", "dev_tools")
		"controls":
			_controls_page()


## Controls: one row per page of the sidebar with the key that opens it. Click a key, then press the new
## one (Esc cancels, Backspace clears). A key already used moves to this page.
func _controls_page() -> void:
	_page.add_child(_note("Each page of the sidebar opens with a key, shown on its tab. Click a key and press a new one: Esc cancels, Backspace or Delete leaves the page without a key. Esc always opens the menu."))
	var list := UI.vbox(4)
	for pair in Options.tab_list():
		var h := UI.hbox(12)
		var l := UI.label(pair[1])
		l.custom_minimum_size.x = 250
		h.add_child(l)
		var code := Options.keybind(pair[0])
		var text := "Press a key…" if _capturing == pair[0] else (Options.key_name(code) if code != 0 else "None")
		var b := UI.button(text, "ChipOn" if _capturing == pair[0] else "Chip")
		b.custom_minimum_size.x = 150
		b.focus_mode = Control.FOCUS_NONE
		b.tooltip_text = "Click, then press the key for %s" % pair[1]
		var tab: String = pair[0]
		b.pressed.connect(func():
			_capturing = "" if _capturing == tab else tab
			_rebuild())
		h.add_child(b)
		list.add_child(h)
	var sc := UI.scroll(list)
	sc.custom_minimum_size.y = 300
	_page.add_child(sc)
	var row := UI.hbox(10)
	row.add_child(UI.spacer())
	row.add_child(UI.button("Reset to defaults", "", func():
		_capturing = ""
		Options.reset_keybinds()
		_rebuild()))
	_page.add_child(row)


## While a key is being chosen, the next key press is the new key and goes nowhere else (not even Esc to
## the dialog, which would close it).
func _input(event: InputEvent) -> void:
	if _capturing == "" or not (event is InputEventKey) or not event.pressed or event.echo:
		return
	get_viewport().set_input_as_handled()
	var code: int = event.keycode
	if code in [KEY_BACKSPACE, KEY_DELETE]:
		Options.set_keybind(_capturing, 0)
	elif code in Options.RESERVED_KEYS or code == KEY_NONE:
		if code != KEY_ESCAPE:
			return   # a modifier on its own: wait for the real key
	else:
		Options.set_keybind(_capturing, code)
	_capturing = ""
	_rebuild()


## A wrapped note with a fixed width. A wrapping label that is measured before its container has given
## it a width reports a height of thousands of pixels, and switching the window mode can make that stick.
func _note(text: String) -> Label:
	return UI.wrap_label(text, "Faint", 600)


func _row(title: String) -> HBoxContainer:
	var h := UI.hbox(12)
	var l := UI.label(title)
	l.custom_minimum_size.x = 250
	h.add_child(l)
	_page.add_child(h)
	return h


func _slider(title: String, key: String) -> void:
	var h := _row(title)
	var s := HSlider.new()
	s.min_value = 0.0
	s.max_value = 1.0
	s.step = 0.01
	s.value = float(Options.get_value(key))
	s.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	s.custom_minimum_size.y = 24
	var pct := UI.label("%d%%" % roundi(s.value * 100), "Num")
	pct.custom_minimum_size.x = 52
	pct.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	s.value_changed.connect(func(v):
		pct.text = "%d%%" % roundi(v * 100)
		Options.set_value(key, v))
	s.drag_ended.connect(func(_c): if key == "sfx" or key == "master": Sfx.play("click"))
	h.add_child(s)
	h.add_child(pct)


func _toggle(title: String, key: String) -> void:
	var c := ToggleSwitch.new()
	c.text = title
	c.button_pressed = bool(Options.get_value(key))
	c.focus_mode = Control.FOCUS_NONE
	c.toggled.connect(func(on): Options.set_value(key, on))
	_page.add_child(c)


func _choice(title: String, key: String, labels: Array, values: Array = []) -> OptionButton:
	var h := _row(title)
	var o := OptionButton.new()
	o.focus_mode = Control.FOCUS_NONE
	o.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	for i in labels.size():
		o.add_item(labels[i], i)
	if key == "":
		o.selected = 0
		h.add_child(o)
		return o
	var current: Variant = Options.get_value(key)
	o.selected = values.find(current) if not values.is_empty() else int(current)
	o.item_selected.connect(func(i):
		Options.set_value(key, values[i] if not values.is_empty() else i)
		if key == "window_mode":
			# after the dropdown has closed and the window has settled into its new mode
			_rebuild.call_deferred())
	h.add_child(o)
	return o
